version: 0.2
phases:
  pre_build:
    commands:
      - echo 'Prebuild phase'
      - echo API_ID = $API_ID
      - echo STAGE_NAME = $STAGE_NAME
  build:
    commands:
      - echo 'Build phase'
      - aws apigateway create-deployment --rest-api-id ${API_ID} --stage-name ${STAGE_NAME}
